apiVersion: v1
data:
  rpj-input.json: |+
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "launchId": {
          "title": "Launch ID",
          "type": "string"
        },
        "epicCode": {
          "title": "Epic code",
          "type": "string"
        },
        "recipients": {
          "title": "Recipients",
          "type": "array",
          "description": "A list of recipients for the notification in the format of 'user:<namespace>/<username>' or 'group:<namespace>/<groupname>', i.e. 'user:default/jsmith'",
          "items": {
            "title": "Recipient",
            "type": "string",
            "pattern": "^(user|group):[a-z0-9]([-a-z0-9]*[a-z0-9])?/([a-z0-9]([-a-z0-9]*[a-z0-9])?)$"
          },
          "minItems": 1
        }
      },
      "required": [
        "launchId",
        "recipients"
      ]
    }

  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "$ref": "../shared/schemas/workflow-result-schema.json",
                "type": "object"
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-rpj-resources-schemas
