apiVersion: v1
data:
  application.properties: |
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: greeting
    sonataflow.org/workflow-app: greeting
  name: greeting-props
