apiVersion: v1
data:
  application.properties: "# Backstage Notifications service\nquarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}\nquarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN:-}\n\n#
    Jira cloud\njira_url=${JIRA_URL}\nquarkus.rest-client.jira_openapi_yaml.url=${JIRA_URL}\nquarkus.openapi-generator.jira_openapi_yaml.auth.basicAuth.username=${JIRA_USERNAME:-}\nquarkus.openapi-generator.jira_openapi_yaml.auth.basicAuth.password=${JIRA_API_TOKEN:-}\n\n#
    OpenShift API Server\nquarkus.rest-client.ocp_project_openapi_yaml.url=${OCP_API_SERVER_URL:-}\nquarkus.openapi-generator.ocp_project_openapi_yaml.auth.BearerToken.bearer-token=${OCP_API_SERVER_TOKEN:-}\nquarkus.tls.trust-all=true\nquarkus.kubernetes-client.trust-certs=true\n\nquarkus.flyway.migrate-at-start=true\n\n#
    This property is used to select the log level, which controls the amount\n# of
    information logged on HTTP requests based on the severity of the events. \n# Possible
    values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL. \n# and see https://quarkus.io/guides/logging
    for documentation \nquarkus.log.category.\"org.apache.http\".level=INFO\nquarkus.log.level=INFO\nquarkus.flyway.migrate-at-start=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: create-ocp-project
    sonataflow.org/workflow-app: create-ocp-project
  name: create-ocp-project-props
