apiVersion: v1
data:
  application.properties: |
    quarkus.rest-client.notifications_openapi_yaml.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator/api/notifications}

    jira_url=${JIRA_URL}
    quarkus.rest-client.jira_openapi_yaml.url=${JIRA_URL}
    quarkus.openapi-generator.jira_openapi_yaml.auth.basicAuth.username=${JIRA_USERNAME:-}
    quarkus.openapi-generator.jira_openapi_yaml.auth.basicAuth.password=${JIRA_API_TOKEN:-}

    # OpenShift API Server
    quarkus.rest-client.ocp_project_openapi_yaml.url=${OCP_API_SERVER_URL:-}
    quarkus.openapi-generator.ocp_project_openapi_yaml.auth.BearerToken.bearer-token=${OCP_API_SERVER_TOKEN:-}
    quarkus.tls.trust-all=true
    quarkus.kubernetes-client.trust-certs=true

    quarkus.flyway.migrate-at-start=true
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: create-ocp-project
    sonataflow.org/workflow-app: create-ocp-project
  name: create-ocp-project-props
