# replacement.yaml

apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replace-config
replacements:
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.instance_name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.name
          - spec.selector.matchLabels.app
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
          - spec.template.spec.containers.0.name
      - select:
          apiVersion: v1
          kind: Service
          name: __instance_name__-svc
        fieldPaths:
          - metadata.name
          - spec.selector.app
      - select:
          apiVersion: route.openshift.io/v1
          kind: Route
        fieldPaths:
          - metadata.name
          - spec.to.name
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.instance_image
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.0.image
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.broker_name
    targets:
      - select:
          kind: Broker
        fieldPaths:
          - metadata.name
      - select:
          kind: Trigger
        fieldPaths:
          - spec.broker
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.workflow_name
      # Could also be taken from the SonataFlow instance, but 
      # ATM it is named just 'm2k' instead of serverless-workflows-m2k
      # kind: SonataFlow
      # name: m2k
      # fieldPath: metadata.name
    targets:
      - select:
          kind: Trigger
        fieldPaths:
          - spec.subscriber.ref.name
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.kfunction_name
    targets:
      - select:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: __kfunction_name__
        fieldPaths:
          - metadata.name
          # - spec.template.metadata.name
      - select:
          kind: Trigger
          name: m2k-save-transformation-event
        fieldPaths:
          - spec.subscriber.ref.name
  - source:
      kind: ConfigMap
      name: move2kube-values
      fieldPath: data.ssh_secret_name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.volumes.[name=ssh-priv-key].secret.secretName
          - spec.template.spec.volumes.[name=ssh-pub-key].secret.secretName
      - select:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: m2k-save-transformation-func
        fieldPaths:
          - spec.template.spec.volumes.[name=ssh-priv-key].secret.secretName
          - spec.template.spec.volumes.[name=ssh-pub-key].secret.secretName
