apiVersion: v1
data:
  application.properties: |2-

    # Configuration for the incoming cloud events received by the serverless workflows.
    mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
    mp.messaging.incoming.kogito_incoming_stream.path=/
    mp.messaging.incoming.kogito_incoming_stream.method=POST

    # This property is used when sending the notification while waiting for Q&A
    move2kube_url={{ .Values.workflow.move2kubeURL }}
    # This property is used to send requests to the move2kube instance
    quarkus.rest-client.move2kube_yaml.url={{ .Values.workflow.move2kubeURL }}
    # This property is used to send requests to the backstage notification plugin
    quarkus.rest-client.notifications.url={{ .Values.workflow.backstageNotificationURL }}
    #quarkus.log.category.\"org.apache.http\".level=DEBUG
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.workflow.name }}
    sonataflow.org/workflow-app: {{ .Values.workflow.name }}
  name: {{ .Values.workflow.name }}-props
  namespace: {{ .Values.namespace }}
