apiVersion: v1
kind: Namespace
metadata:
  name: openshift-mta
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-mta
  namespace: openshift-mta
spec:
  targetNamespaces:
  - openshift-mta
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: openshift-mta
spec:
  channel: stable-v6.2
  installPlanApproval: Automatic
  name: mta-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
