apiVersion: v1
data:
  application.properties: |
    # MTA
    mta.url = ${MTA_URL:http://mta-ui.openshift-mta.svc.cluster.local:8080}
    quarkus.rest-client.mta_json.url = ${mta.url}

    # Backstage Notifications service
    quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}
    quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mta-analysis-v6
    sonataflow.org/workflow-app: mta-analysis-v6
  name: mta-analysis-v6-props
