apiVersion: v1
data:
  application.properties: "# MTA\nmta.url = ${MTA_URL:http://mta-ui.openshift-mta.svc.cluster.local:8080}\nquarkus.rest-client.mta_json.url
    = ${mta.url}/hub\n#quarkus.rest-client.mta_json.auth.basicAuth.username = username\n#quarkus.rest-client.mta_json.auth.basicAuth.password
    = password\n\n# Backstage Notifications service\nquarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}\nquarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}\n\n#
    This property is used to select the log level, which controls the amount\n# of
    information logged on HTTP requests based on the severity of the events. \n# Possible
    values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL. \n# and see https://quarkus.io/guides/logging
    for documentation \nquarkus.log.category.\"org.apache.http\".level=INFO\nquarkus.log.level=INFO\nquarkus.flyway.migrate-at-start=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mtaanalysis
    sonataflow.org/workflow-app: mtaanalysis
  name: mtaanalysis-props
