apiVersion: v1
data:
  application.properties: |
    mta.url = ${MTA_URL:http://mta-ui.openshift-mta.svc.cluster.local:8080}
    quarkus.rest-client.mta_json.url = ${mta.url}/hub
    quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator/api/notifications/}
    #quarkus.rest-client.mta_json.auth.basicAuth.username = username
    #quarkus.rest-client.mta_json.auth.basicAuth.password = password

    #quarkus.log.category.\"org.apache.http\".level = DEBUG
    quarkus.flyway.migrate-at-start=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mtaanalysis
    sonataflow.org/workflow-app: mtaanalysis
  name: mtaanalysis-props
