apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  annotations:
    sonataflow.org/description: YAML based greeting workflow
    sonataflow.org/expressionLang: jsonpath
    sonataflow.org/version: "1.0"
  creationTimestamp: null
  labels:
    app: greeting
    sonataflow.org/workflow-app: greeting
  name: greeting
  namespace: default
spec:
  flow:
    dataInputSchema:
      failOnValidationErrors: true
      schema: specs/greeting.sw.input-schema.json
    functions:
      - name: greetFunction
        operation: sysout
        type: custom
    start:
      stateName: ChooseOnLanguage
    states:
      - dataConditions:
          - condition: ${$.[?(@.language  == 'English')]}
            transition:
              nextState: GreetInEnglish
          - condition: ${$.[?(@.language  == 'Spanish')]}
            transition:
              nextState: GreetInSpanish
        defaultCondition:
          transition:
            nextState: GreetInEnglish
        name: ChooseOnLanguage
        type: switch
      - data:
          greeting: 'Hello from YAML Workflow, '
        name: GreetInEnglish
        transition:
          nextState: GreetPerson
        type: inject
      - data:
          greeting: 'Saludos desde YAML Workflow, '
        name: GreetInSpanish
        transition:
          nextState: GreetPerson
        type: inject
      - actionMode: sequential
        actions:
          - actionDataFilter:
              useResults: true
            functionRef:
              arguments:
                message: $.greeting $.name
              invoke: sync
              refName: greetFunction
            name: greetAction
        end:
          terminate: true
        name: GreetPerson
        type: operation
  podTemplate:
    container:
      resources: {}
      image: quay.io/orchestrator/serverless-workflow-greeting:8dc7224f47325e380e72ac4555f4b2aa1d129e8a
  resources:
    configMaps:
      - configMap:
          name: 01-greeting-resources
        workflowPath: specs
status:
  address: {}
  lastTimeRecoverAttempt: null
