apiVersion: v1
data:
  application.properties: "quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}\nquarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}\nquarkus.rest-client.mtv_yaml.url=${OCP_API_SERVER_URL}\nquarkus.openapi-generator.mtv_yaml.auth.BearerToken.bearer-token=${OCP_API_SERVER_TOKEN}\nquarkus.tls.trust-all=true\nquarkus.kubernetes-client.trust-certs=true\n\n#
    This property is used to select the log level, which controls the amount\n# of
    information logged on HTTP requests based on the severity of the events. \n# Possible
    values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL. \n# and see https://quarkus.io/guides/logging
    for documentation \nquarkus.log.category.\"org.apache.http\".level=INFO\nquarkus.log.level=INFO\nquarkus.flyway.migrate-at-start=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: mtv-migration
    sonataflow.org/workflow-app: mtv-migration
  name: mtv-migration-props
