sshSecretName: sshkeys # name of the secret holding the ssh keys that will be used by move2kube resources
brokerName: m2k-default # name of the broker used by Knative eventing resources
brokerURL: http://broker-ingress.knative-eventing.svc.cluster.local/sonataflow-infra/m2k-default
workflow:
  name: m2k # name of the workflow
  move2kubeURL: https://move2kube-route-sonataflow-infra.apps.cluster-8xfw.redhatworkshops.io # URL for move2kube instance
  backstageNotificationURL: http://orchestrator-backstage.orchestrator:7007/api/notifications/ # URL for backstage notification plugin
kfunction:
  name: m2k-save-transformation-func # name of the Knative function that save the transformation output to git
  image: quay.io/orchestrator/serverless-workflow-m2k-kfunc:eb524f243974b9cb34391b411a271b19bfd18cb5 # image of the knative function
instance:
  name: move2kube # name of the move2kube instance deployment
  image: quay.io/konveyor/move2kube-ui:v0.3.14-rc.0 # image of the move2kube instance
  namespace: move2kube
