apiVersion: v1
data:
  ticket-escalation-schema.json: |-
    {
      "$id": "classpath:/schemas/ticket-escalation-schema.json",
      "title": "Ticket escalation: Data Input Schema",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Name of the requested namespace"
        }
      },
      "examples": [
        {
          "namespace": "a-namespace"
        }
      ]
    }
  ticket-escalation_sub_schema.json: |-
    {
      "$id": "classpath:/schemas/ticket-escalation_sub_schema.json",
      "title": "ticketEscalation: Input Section",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string",
          "description": "Name of the requested namespace"
        }
      },
      "required": [
        "namespace"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 02-ticketescalation-resources
