apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jira-listener
  labels:
    app: jira-listener
spec:
  template:
    metadata:
      labels:
        app: jira-listener
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: jira-listener-image
          imagePullPolicy: Always
          name: jira-listener
          resources:
            limits:
              memory: 200Mi
