---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  labels:
    app: event-display
spec:
  template:
    metadata:
      labels:
        app: event-display
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          name: event-display
          resources:
            limits:
              memory: 200Mi
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: ticket-events
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ticket-closed
spec:
  broker: ticket-events
  filter:
    attributes:
      type: dev.parodos.escalation
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: ticketescalation
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  broker: ticket-events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: ticket-source
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: jira-listener
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: ticket-events
