apiVersion: v1
data:
  application.properties: "# Backstage Notifications service\nquarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}\nquarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}\n\nvm_check_running_max_retries=${VM_CHECK_RUNNING_MAX_RETRIES:10}\n\n#
    Jira cloud\njira_url=${JIRA_URL:https://<site-url>}\nquarkus.rest-client.jira_openapi_json.url=${JIRA_URL:https://<site-url>}\nquarkus.openapi-generator.jira_openapi_json.auth.basicAuth.username=${JIRA_USERNAME:-}\nquarkus.openapi-generator.jira_openapi_json.auth.basicAuth.password=${JIRA_API_TOKEN:-}\n\n#
    OpenShift API Server\ncluster_console_url=${OCP_CONSOLE_URL:-}\nquarkus.rest-client.kubevirt_openapi_yaml.url=${OCP_API_SERVER_URL:-}\nquarkus.openapi-generator.kubevirt_openapi_yaml.auth.BearerToken.bearer-token=${OCP_API_SERVER_TOKEN:-}\nquarkus.tls.trust-all=true\nquarkus.kubernetes-client.trust-certs=true\n\nquarkus.flyway.migrate-at-start=true\n\n#
    This property is used to select the log level, which controls the amount\n# of
    information logged on HTTP requests based on the severity of the events. \n# Possible
    values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL. \n# and see https://quarkus.io/guides/logging
    for documentation \nquarkus.log.category.\"org.apache.http\".level=INFO\nquarkus.log.level=INFO\nquarkus.flyway.migrate-at-start=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: modify-vm-resources
    sonataflow.org/workflow-app: modify-vm-resources
  name: modify-vm-resources-props
