apiVersion: v1
data:
  greeting.sw.input-schema.json: |
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "language": {
          "title": "Language",
          "description": "Language to greet",
          "type": "string",
          "enum": ["English", "Spanish"],
          "default": "English"
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-greeting-resources
