apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-configmap_01-greeting-resources.yaml
- 01-sonataflow_greeting.yaml

namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: greeting
images:
- name: serverless-workflow-greeting
  newName: quay.io/orchestrator/serverless-workflow-greeting
  newTag: f6fbb19dd531f5bcb612b28862a2303dfae87bd7
