apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: m2k
  annotations:
    sonataflow.org/profile: prod
spec:
  podTemplate:
    container:
      image: serverless-workflow-greeting
      resources: {}
