apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: ticketescalation
spec:
  podTemplate:
    container:
      image: serverless-workflow-escalation
      envFrom:
      - configMapRef:
          name: escalation-config
      - secretRef:
          name: escalation-secret
      resources: {}
