apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.instance.name }}-route
  namespace: {{ .Values.instance.namespace }}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.instance.name }}-svc
