apiVersion: v1
data:
  application.properties: "\n# Configuration for the incoming cloud events received
    by the serverless workflows.\nmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http\nmp.messaging.incoming.kogito_incoming_stream.path=/\nmp.messaging.incoming.kogito_incoming_stream.method=POST\n\n#
    This property is used when sending the notification while waiting for Q&A\nmove2kube_url=${MOVE2KUBE_URL:http://move2kube-svc.move2kube.svc.cluster.local:8080}\nmove2kube_get_plan_max_retries=${MOVE2KUBE_GET_PLAN_MAX_RETRIES:10}\n\n#
    This property is used to send requests to the move2kube instance\nquarkus.rest-client.move2kube_yaml.url=${MOVE2KUBE_URL:http://move2kube-svc.move2kube.svc.cluster.local:8080}\n\n#
    This property is used to send requests to the backstage notification plugin\nquarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}\nquarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}\n\n#
    This property is used to select the log level, which controls the amount\n# of
    information logged on HTTP requests based on the severity of the events. \n# Possible
    values: OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL. \n# and see https://quarkus.io/guides/logging
    for documentation \nquarkus.log.category.\"org.apache.http\".level=INFO\nquarkus.log.level=INFO\nquarkus.flyway.migrate-at-start=true\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: m2k
    sonataflow.org/workflow-app: m2k
  name: m2k-props
