apiVersion: v1
data:
  request-vm-cnv__main-schema.json: |
    {
      "$id": "classpath:/schemas/request-vm-cnv-schema.json",
      "title": "Data input schema",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "inputs": {
          "title": "Inputs",
          "type": "object",
          "properties": {
            "projectKey": {
              "title": "Project Key",
              "description": "JIRA project key",
              "type": "string"
            },
            "vm_namespace": {
              "title": "VM Namespace",
              "description": "Namespace in which create the VM",
              "type": "string",
              "default": "default",
              "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            },
            "vm_name": {
              "title": "VM Name",
              "description": "Name of the VM to create",
              "type": "string",
              "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            },
            "vm_image": {
              "title": "VM Image",
              "description": "Image to use to create the VM",
              "type": "string",
              "enum": ["centos-stream8","centos-stream9","centos7","fedora","rhel7","rhel8","rhel9"]
            }
          },
          "required": [
            "projectKey",
            "vm_name",
            "vm_image",
            "vm_namespace"
          ]
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-request-vm-cnv-resources
