name: Release Helm chart for greeting workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/greeting/**'
      - '.github/workflows/greeting.yaml'
      - '.github/workflows/release.yaml'

jobs:
  release-greeting:
    uses: ./.github/workflows/release.yaml
    with:
      workflow_id: greeting
    secrets: inherit

